telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}

spring:
  dotenv:
    enabled: true
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update


link:
  address: ${REST_SERVICE_URL}

salt: ${SALT}



