spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update

server:
  port: 8086


salt: ${SALT}